{% set name = "cdsodatacli" %}
{% set version = "2023.12.12.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdsodatacli-{{ version }}.tar.gz
  sha256: 8c984e376b0ae906ea054fcc375bd90c8051a0d0a03700b7ac614251baec19b6

build:
  entry_points:
    - queryCDS = cdsodatacli.query:query_client
    - downloadFromCDS = cdsodatacli.download:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - geopandas
    - numpy
    - requests
    - shapely
    - tqdm
    - pyyaml

test:
  imports:
    - cdsodatacli
  commands:
    - pip check
    - queryCDS --help
    - downloadFromCDS --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/cdsodatacli
  summary: OData client for Copernicus Data Space catalog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
